### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by flanfly** [das-labor/server#8]
- [ ] Postfix SSL only w/ LDAP #35
- [ ] Dovecot SSL only w/ LDAP, POP3 & IMAP4 #35
- [x] Spamassasin
- [ ] DKIM #35 (dkim.key)
- [ ] fail2ban
- [ ] Mailman 3
- [x] SPF
- [ ] sieve filter
